:sparkles: POST /api/preview
Zenika/react-workbench pull request #121
Opened 2017-08-15 15:25 UTC by fabienjuif

2017-08-15 15:25 UTC, fabienjuif commented on src/script/server/api/services/doc/docgen/docgen.spec.js
> +    expect(fs.readFileAsync.mock.calls.length).toBe(1)
@bpetetot Do you have an idea about this ?

2017-08-15 15:25 UTC, fabienjuif commented on src/script/server/api/services/doc/docgen/docgen.spec.js
> +    expect(fs.readFileAsync.mock.calls.length).toBe(1)
@bpetetot Do you have an idea about this ?

2017-08-16 08:49 UTC, fabienjuif commented on src/script/server/api/services/doc/docgen/docgen.spec.js
> +    expect(fs.readFileAsync.mock.calls.length).toBe(1)
Ok catch it ^^

2017-08-16 08:49 UTC, fabienjuif commented on src/script/server/api/services/doc/docgen/docgen.spec.js
> +    expect(fs.readFileAsync.mock.calls.length).toBe(1)
Ok catch it ^^

2017-08-16 08:50 UTC, fabienjuif commented
@bpetetot can you review this so I can finish gui impacts ?

2017-08-16 09:03 UTC, bpetetot requested changes

2017-08-16 09:03 UTC, bpetetot commented on src/script/server/api/interfaces/props.js
> +  handler: async () => doc.docgen(),
doesn't need to be async

2017-08-16 09:03 UTC, bpetetot commented on src/script/server/api/interfaces/readme.js
> +  handler: async () => doc.markdown(),
doesn't need to be async

2017-08-16 09:03 UTC, bpetetot commented on src/script/server/api/services/doc/html/html.js
> +module.exports = source => async () => {
why is it async ?

2017-08-16 09:22 UTC, bpetetot approved these changes
👌

2017-08-16 09:27 UTC, merged