:sparkles: save readme button
Zenika/react-workbench pull request #128
Opened 2017-09-01 14:47 UTC by bpetetot

**Description**
Add the save button of the readme documentation field. (only GUI part)
Call the endpoint `POST /api/readme`

2017-09-01 14:48 UTC, bpetetot commented
Can you just check about how I am using saga in this simple case ?
To be sure that I'm doing it in the right way. :)

2017-09-03 15:56 UTC, fabienjuif commented on src/gui/sagas/documentation/readme.js
> +  fetch('/api/readme', { method: 'POST', body: state })
Look at `yield call` so test are easier to write :)

2017-09-03 15:57 UTC, fabienjuif commented on src/gui/screens/documentation/actions/actions.jsx
> +    <div>
Why do you wrap it to a div ?

2017-09-03 15:58 UTC, fabienjuif commented on src/gui/screens/documentation/actions/actions.jsx
> +export default Actions
I think this a good practice to always use `onlyUpdateForPropTypes` from `recompose`

https://github.com/Zenika/react-workbench/blob/master/src/gui/screens/workbench/state/state.jsx#L32

2017-09-03 15:59 UTC, fabienjuif requested changes
Some comments.
If you use sagas effects, tests are easier to write, espacially with trampss-redux-saga-tester :)

2017-09-19 10:19 UTC, merged