:sparkles: Extract proptypes of components with HOCs
Zenika/react-workbench pull request #49
Opened 2017-04-28 09:30 UTC by bpetetot

#48

2017-04-28 14:23 UTC, fabienjuif commented on package.json
> +    "whatwg-fetch": "^2.0.3"
`babel-polyfill`

2017-04-28 14:26 UTC, fabienjuif commented on src/server/api/models/docgen/service.js
> +    visitFunctionDeclaration: false,
Try the default definition, if this is `false` you could delete those lines

2017-04-28 14:27 UTC, fabienjuif commented on src/server/api/models/docgen/service.js
> +    visitExportDeclaration: false,
What about this one ?

2017-04-28 14:29 UTC, fabienjuif commented on src/server/api/models/docgen/service.js
> +      // file path not found
😨

2017-04-28 14:33 UTC, fabienjuif commented on src/server/api/models/docgen/service.js
> +            // Manage imported components in HOC from different file
Why do you pass by an exception instead of recalling `exportDeclaration(newPath)`

2017-04-28 14:36 UTC, fabienjuif commented on src/server/api/models/docgen/service.js
> +        return resolvePath(p.resolve(path, 'index.js'))
`return resolvePath(p.resolve(path, 'index'))
`

2017-04-28 14:39 UTC, fabienjuif commented on src/server/api/models/docgen/service.js
> +  for (let i = 0; i < extensions.length; i += 1) {
`for of`

2017-04-28 14:53 UTC, fabienjuif commented on src/server/api/models/docgen/service.js
> +const resolveHOC = require('react-docgen/dist/utils/resolveHOC.js').default
you don't need that `.js`

2017-04-28 14:54 UTC, fabienjuif commented on src/server/api/models/docgen/service.js
> +const isComponentDefinition = (path) => {
Add the source (url) in a commentary in this file

2017-04-28 14:55 UTC, fabienjuif commented on src/server/api/models/docgen/service.js
> +      // file path not found
Ignore only 1 error, you have to throw the others

2017-04-28 15:00 UTC, fabienjuif requested changes
See above commentaries

2017-04-30 09:54 UTC, bpetetot commented on src/server/api/models/docgen/service.js
> +  for (let i = 0; i < extensions.length; i += 1) {
forbidden by the linter : 
`[eslint] iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations. (no-restricted-syntax)`

here the airbnb explanation : 
https://github.com/airbnb/javascript/issues/1271

2017-04-30 09:54 UTC, bpetetot commented on src/server/api/models/docgen/service.js
> +      // file path not found
I don't understand your last comment

2017-04-30 21:05 UTC, fabienjuif commented on src/server/api/models/docgen/service.js
> +      // file path not found
Like we did there : https://github.com/Zenika/react-workbench/blob/master/src/server/api/ddb/ddb.js#L12

2017-05-01 14:09 UTC, bpetetot commented
@fabienjuif ready to review

2017-05-02 07:06 UTC, fabienjuif approved these changes

2017-05-02 15:50 UTC, merged