:bug: fix(#22)
Zenika/react-workbench pull request #68
Opened 2017-05-08 21:07 UTC by bpetetot

#22

2017-05-08 21:11 UTC, bpetetot commented
@fabienjuif : I have added all tests for `modules.js` with 100% coverage :)
Can you tell me what do think about it please ? (about technical implementation and use cases)

2017-05-09 10:10 UTC, fabienjuif commented on src/server/webpack/modules.spec.js
> +  it('should show warning when node_modules not found', async () => {
I would add a `describe('errors', () => {` to handle errors.

2017-05-09 10:11 UTC, fabienjuif commented on src/server/webpack/modules.spec.js
> +    // calls
If there is no error your test will pass.
That's why I use a boolean to test this kind of code : 
```es6
error = false
try {
// ...
} catch (ex) {
error = true
// ...
}
expect(error).toBe(true)
```

2017-05-09 10:12 UTC, fabienjuif requested changes
Great :)

I think we don't have a test that iterate more than once on the path finding.

2017-05-09 12:12 UTC, bpetetot commented
@fabienjuif : tests updated, you can do a final check

2017-05-09 12:25 UTC, bpetetot commented
@fabienjuif : done

2017-05-09 12:31 UTC, fabienjuif commented on src/server/webpack/modules.spec.js
> +  it('should iterate over the path until it finds a package.json file', async () => {
👍

2017-05-10 05:58 UTC, fabienjuif approved these changes
Waiting for coverage

2017-05-10 14:27 UTC, merged