:white_check_mark: 'fs' service api
Zenika/react-workbench pull request #74
Opened 2017-05-12 13:30 UTC by bpetetot

#6

2017-05-16 06:50 UTC, fabienjuif commented on src/server/api/models/fs/fs.spec.js
> +    fs.readdirAsync.mockImplementation(jest.fn(async () => ['baz.txt']))
You can use this it to test `isDirectory : false`

2017-05-16 06:51 UTC, fabienjuif commented on src/server/api/models/fs/fs.spec.js
>  })
One test is missing to me : that stats properties are cloned into the return value.

2017-05-16 06:51 UTC, fabienjuif requested changes
See comments

2017-06-02 09:31 UTC, fabienjuif approved these changes

2017-06-02 09:53 UTC, bpetetot commented
@fabienjuif you can check it

2017-06-02 12:18 UTC, merged