:sparkles: markdown and readme api
Zenika/react-workbench pull request #91
Opened 2017-07-05 13:51 UTC by bpetetot

#60

2017-07-05 17:11 UTC, bpetetot commented
**New APIs :**
- **`GET /api/readme` :**  retrieve current README.md file content of the component _(if exists)_
- **`POST /api/readme` :** create / save the README.md file of the component with given content
- **`POST /api/markdown`:** generate the markdown from given component docgen

**The goal of these APIs is to have the following process _(in a next PR)_ :** 
1.  The user will click on a button `documentation`
2. It calls **`GET /api/readme`**
     - if _README.md_ already exists => display existing markdown in a markdown editor
     - else call **`POST /api/markdown`** => put generated markdown in a markdown editor
3. The user can update the component documentation through the editor
     - a `save` button will call **`POST /api/readme`** and save / create the README.md file

**I would like also to have buttons in the markdown editor to add some generated parts _(in a next PR)_ :** 
- `Add description` : will add the description where the cursor is in the editor
- `Add props`: will add the component props documentation where the cursor is in the editor
- `Add screenshot` : will add a component screenshot where the cursor is in the editor

To make the `Add description` and `Add props` buttons, I will need to improve API **`POST /api/markdown`** adding some query parameters : 
**`POST /api/markdown?q=props`**

2017-07-06 07:14 UTC, fabienjuif commented
I asking myself about endpoints names.
Why don't we use:
 -  **```/api/file```** (to replace **`/api/makrdown`**), and make it more generic
    - **`POST /api/file/readme.md`** by example
 - **```GET /api/documentation```** to generate the documentation, 
    - **`GET /API/documentation?format=markdown|text|html`**

The endpoints don't have to be about format but about their purpose don't you think ?

2017-07-06 07:16 UTC, fabienjuif commented on src/script/server/api/services/markdown/docgen2markdown.js
> +const generateTitle = (name) => {
Why don't we do it in a oneliner ?

2017-07-06 07:17 UTC, fabienjuif commented on src/script/server/api/services/markdown/docgen2markdown.js
> +  return `# ${name}\n\n`
I think the \n\n shouldn't be there but into the default exports.

2017-07-06 07:18 UTC, fabienjuif commented on src/script/server/api/services/markdown/docgen2markdown.js
> +  let markdown = ''
If we delete `\n\n` ending from other functions we could do : 
```es6
module.exports = (name, doc) => `
${generateTitle(name)}

${generateDescription(doc.description)}
`

2017-07-06 07:34 UTC, fabienjuif requested changes
Great work, once again :)

I start arguing about endpoints

2017-07-06 15:01 UTC, bpetetot commented
Good idea !
We can also merge **`/api/file`** with the current **`/api/fs`**
_Examples :_
- **`GET /api/fs/foo/bar`** will list folder `/foo/bar`
- **`GET /api/fs/foo/bar/README.md`** will get README.md file content
- **`POST /api/fs/foo/bar/README.md`** will create / update README.md file
- ...

And I'm agree about being agnostic about the format with API documentation

2017-07-06 15:04 UTC, fabienjuif commented
Yeah I agree about merging both endpoints

2017-07-07 15:15 UTC, bpetetot commented
@fabienjuif you can check it

2017-07-10 12:59 UTC, fabienjuif commented on src/script/server/api/services/fs/service.js
> +const statFile = (fullpath, stats, content) => Object.assign(
You can merge master then use spread operator

2017-07-10 14:28 UTC, fabienjuif approved these changes
👌 you rock

2017-07-10 14:48 UTC, merged