:wrench: build script -> rest/spread properties
Zenika/react-workbench pull request #92
Opened 2017-07-06 12:44 UTC by fabienjuif

Drawbacks : 
 - Build time
 - Slow startup

What to improve (in an other PR) : 
 - Have a specific babelrc to transpile src/script so it doesn't transpile async/await by example and the startup could be faster

2017-07-06 14:11 UTC, bpetetot requested changes

2017-07-06 14:11 UTC, bpetetot commented on package.json
>      "start": "./src/script/index.js",
now it's `"start": "index.js",`

2017-07-06 14:11 UTC, bpetetot commented on package.json
> +    "build:script:dev": "npm run build:script:prod -- -w",
I've got a build error in watch mode for the script.
When I want to update a file, I have this error : 
```
🚨   Could not load fs (imported by /Users/zuhmilo/workspaces/workspace-perso/react-workbench/src/script/config/bluebird.js): ENOENT: no such file or
 directory, open 'fs'
```

I think we need a [rollup plugin](https://github.com/calvinmetcalf/rollup-plugin-node-builtins), or put the platform target in babel configuration to node

2017-07-06 14:33 UTC, fabienjuif commented on package.json
> +    "build:script:dev": "npm run build:script:prod -- -w",
Weird I didn't have the problem.
I'll look into it

2017-07-06 14:38 UTC, fabienjuif commented
@bpetetot I let you try the `build:script:dev` since I can't reproduce it

2017-07-06 15:24 UTC, bpetetot commented
@fabienjuif 
I've got an other error
```
🚨   Could not load react-docgen/dist/utils (imported by /Users/zuhmilo/workspaces/workspace-perso/react-workbench/src/script/server/api/services/doc
gen/resolvers/componentResolver.js): ENOENT: no such file or directory, open 'react-docgen/dist/utils'
```

Did you try to modify a file with watching mode enabled ?

2017-07-07 08:49 UTC, fabienjuif commented
Poop PR, new one is #93

2017-07-07 08:49 UTC, closed without merging